session-05/assignments/hw/inventory_app/customerapp/urls.py
from django.urls import include, path, re_path

from . import views
from customerapp.views import IndexView
from django.contrib.auth import views as auth_views

from customerapp.views import IndexView, CustomerListView, CustomerDetailView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView

app_name = 'customerapp'

urlpatterns = [
    # path('', IndexView.as_view(), name='index'),
    path('', CustomerListView.as_view(), name='customers'),

    # LEAKS DATA
    # path('new-customer', CustomerCreateView.as_view(), name='new-customer'),
    # re_path(r'^new-customer', CustomerCreateView.as_view(), name='new-customer'),

    path('<pk>', CustomerDetailView.as_view(), name='customer-detail'),
    path('<pk>/customer-update', CustomerUpdateView.as_view(), name='customer-update'),
    path('<pk>/customer-delete', CustomerDeleteView.as_view(), name='customer-delete'),

    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name='logout'),

    # path('accounts/profile/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),

    # re_path(r'^register/$', views.register, name='register'),
    # re_path(r'^register/$', views.register, name='register')

    # re_path(r'^new-customer/$', views.new_customer, name='new-customer'),

    re_path(r'^new-customer/$', CustomerCreateView.new_customer, name='new-customer'),

]

session-05/assignments/hw/inventory_app/inventory_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productapp.urls')),
    path('customers/', include('customerapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

session-05/assignments/hw/inventory_app/productapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views
from productapp.views import IndexView, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView
from productapp.views import CategoryListView, CategoryDetailView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView

from django.contrib.auth import views as auth_views

app_name = 'productapp'

urlpatterns = [

    # UPDATING TO generic class based views
    #
    # path('', views.index, name='index'),
    # path('catalog/', views.catalog, name='catalog'),
    # path('catalog/<int:id>', views.catalog_detail, name='catalog-detail'),
    # path('catalog/create-product', views.create_product, name='create-product'),


    path('', IndexView.as_view(), name='index'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('catalog/<pk>', ProductDetailView.as_view(), name='catalog-detail'),
    path('create-product', ProductCreateView.as_view(), name='create-product'),
    path('catalog/<pk>/update', ProductUpdateView.as_view(), name='product-update'),
    path('catalog/<pk>/delete', ProductDeleteView.as_view(), name='product-delete'),

    # catalog/category/ --> ERROR is looking for id
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/new', CategoryCreateView.as_view(), name='new-category'),

    path('category/<pk>', CategoryDetailView.as_view(), name='category-detail'),
    path('category/<pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),


    # path('category/<slug>', CategoryDetailView.as_view(), name='category-detail'),
    # path('category/<slug>/update', CategoryUpdateView.as_view(), name='category-update'),
    # path('category/<slug>/delete', CategoryDeleteView.as_view(), name='category-delete'),


    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name='logout'),

    # path('accounts/profile/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),

    re_path(r'^register/$', views.register, name='register'),
]

session-05/assignments/hw/inventory_app/productapp/models.py
from django.db import models
from customerapp.models import Customer


class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a category (e.g. Outdoors)')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
#
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
#
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('productapp:product_list_by_category', args=[self.slug])


# Create your models here.
class Product(models.Model):

    AUTO        = 'Auto'
    BEAUTY      = 'Beauty'
    GROCERIES   = 'Groceries'
    OUTDOORS    = 'Outdoors'
    TECH        = 'Tech'

    CATEGORY_CHOICES = [
        (AUTO, 'Auto'),
        (BEAUTY, 'Beauty'),
        (GROCERIES, 'Groceries'),
        (OUTDOORS, 'Outdoors'),
        (TECH, 'Tech'),
    ]
    # customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    price =  models.FloatField()
    # category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default=TECH)

    # category = models.ForeignKey(Category, help_text='Select a genre for this book', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')

    photo = models.ImageField(upload_to='products', blank=True) # TODO: fix photo not being able to load in form

    def __str__(self):
        return self.name

session-05/assignments/hw/inventory_app/productapp/forms.py
from django.forms import ModelForm
from productapp.models import Product, Category

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


from django import forms

class ProductForm(forms.ModelForm):
    photo = forms.FileField()
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'photo']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'slug']




class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

session-05/assignments/hw/inventory_app/productapp/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse, reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from productapp.models import Product, Category

from .forms import ProductForm, CategoryForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


from .forms import CustomUserCreationForm
from django.contrib import messages


# FUNCTION BASED VIEWS
# (UPDATING TO) generic class based views
# def index(request):
#     return HttpResponse('Welcome Home')

# def catalog(request):
#     products = Product.objects.all()
#     context = {'products': products}
#     return render(request, 'productapp/catalog.html', context)

# def catalog_detail(request, id):
#     product = Product.objects.get(pk=id)
#     context = {'product': product}
#     return render(request, 'productapp/catalog_detail.html', context)

# def create_product(request):
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         print(form)
#         print(form.is_valid()) # why is FORM NOT VALID ?? it’s meaningless to validate a form with no data, f.is_valid() --> false
#         if form.is_valid():
#             product = form.save(commit=False)
#             product.save()
#             return render(request, 'productapp/create_product.html', {'form':form})
#         # else:
#         #     form = ProductForm()
#         #     return render(request, 'productapp/create_product.html', {'form': form})
#
#     else:
#         form = ProductForm()
#         return render(request, 'productapp/create_product.html', {'form': form})


# Base Class View
class IndexView(View):
    def get(self, request, *args, **kwargs):
        # return HttpResponse('Welcome Home to Class Views!')
        return render(request, 'productapp/index.html')


# Generic Class View
class ProductListView(ListView):
    model = Product
    # paginate_by = 2
    context_object_name = 'products'

class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['product_list'] = Product.objects.all()
        return context

# class ProductCreateView(CreateView): # updated to require login
class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['name', 'description', 'price', 'category', 'photo']
    template_name = 'productapp/create_product.html'
    success_url = reverse_lazy('productapp:catalog')
    login_url = '/login/'
    # login_url = 'login'# appname:viewname accounts/login

    # def form_valid(self, form): #MRO
    #     # form.instance.user = self.request.user # logged in user
    #     return super(ProductCreate, self).form_valid(form)


# class ProductUpdateView(UpdateView): # updated to require login
class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'description', 'price', 'category', 'photo']
    template_name = 'productapp/product_update.html'
    success_url = reverse_lazy('productapp:catalog')
    template_name_suffix = '_update_form'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['product_list'] = Product.objects.all()
        return context


# class ProductDeleteView(DeleteView): # updated to require login
class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('productapp:catalog')
    template_name = 'productapp/product_confirm_delete.html'
    login_url = '/login/'



# class CategoryProductListView(ListView):
#     model = Product
#     # paginate_by = 2
#     context_object_name = 'products'
#
#     def get_context_data(self, **kwargs):
#         # Call the base implementation first to get a context
#         context = super().get_context_data(**kwargs)
#         context['category_list'] = Product.objects.all()



class CategoryListView(ListView):
    model = Category
    # paginate_by = 2
    context_object_name = 'categories'
    template_name = 'productapp/category_list.html'

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'productapp/category_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
<<<<<<< HEAD
        context['category_list'] = Product.objects.all()
        # context['prodcuts_list'] = Product.objects.filter_by(category_id=2)

=======
        context['product_list'] = Product.objects.all()
        # context['category_list'] = Category.objects.all()
>>>>>>> session-5
        return context

# class CategoryCreateView(CreateView): # updated to require login
class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name', 'slug']
    template_name = 'productapp/new_category.html'
    success_url = reverse_lazy('productapp:catalog')
    login_url = '/login/'



# class CategoryUpdateView(UpdateView): # updated to require login
class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['name', 'slug']
    template_name = 'productapp/category_update.html'
    success_url = reverse_lazy('producapp:catalog')
    template_name_suffix = '_update_form'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

# class CategoryDeleteView(DeleteView):
class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'productapp/category_confirm_delete.html'
    success_url = reverse_lazy('productapp:catalog')
    login_url = '/login/'
#
# class LoginView(LoginRequiredMixin, View):
#     login_url = '/login/'
#     redirect_field_name = 'index'
#
# class LogoutView(LoginRequiredMixin, View):
#     login_url = '/login/'
#     redirect_field_name = 'index'



def register(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return HttpResponseRedirect(reverse_lazy('productapp:login'))
        else:
            return HttpResponse('Form not valid')
    else:
        f = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': f})

session-05/assignments/hw/inventory_app/productapp/templates/productapp/catalog.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Catalog List</title>
  </head>
  <body>
    <h1>Product Catalog</h1>
  <h3>Add <a href="{% url 'productapp:create-product' %}">New Product</h3></a>
      {% for item in products %}
      <a href="{% url 'productapp:catalog-detail' item.id %}"><h3>{{item.name}}</h3></a>
        <ul>
          <!-- TODO: figure out why this catch doesn't solve issue for object with no photo.
            need to find out why photo is not being accepted
        -->
          {% if item.photo %}
            <img src="{{item.photo.url}}" alt="My Image" height="175" width="175">
          {% else %}
            <li>No photo available</li>

          <li>Description: {{item.description}}</li>
          <li>Price: ${{item.price}}</li>


          <li>Category: {{item.category}}</li>

        </ul>
      {% endfor %}
  </body>
</html>

session-05/assignments/hw/inventory_app/productapp/templates/productapp/catalog_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CATALOG DETAIL </title>
  </head>
  <body>
    <h1>{{product.name}}</h1>
        <ul>
          <li>{{product.description}}</li>
          <li>{{product.price}}</li>
          <li>{{product.category}}</li>
          <li>{{product.photo}}</li>
        </ul>
      <h3>Go back to <a href="{% url 'productapp:catalog' %}">Catalog</a></h3>
  </body>
</html>

session-05/assignments/hw/inventory_app/productapp/templates/productapp/category_confirm_delete.html
{% extends 'base_confirm_delete.html' %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/category_detail.html
{% extends 'base_detail.html' %}

{% block content %}
    <h1>{{object.name}}</h1>
        <ul>
          <li>{{object.slug}}</li>
        </ul>
        <a href="{% url 'productapp:category-update' object.id %}"><h5>UPDATE</h5></a>
        <a href="{% url 'productapp:category-delete' object.id %}"><h5>DELETE</h5></a>

      <h3>Go back to <a href="{% url 'productapp:catalog' %}">Catalog</a></h3>
    <a href="{% url 'productapp:index' %}">  <h3>Go HOME</a></h3>

    <h2>List of Tech Products</h2>
    <p>
      {% for product in product_list %}
        {% if product.category|lower == object.slug %}
            {% if product.photo %}
              <img src="{{product.photo.url}}" alt="My Image" height="175" width="175">
            {% else %}
            <em>No photo available</em>  
            {% endif %}
            <br>
          Name:
              <a href="{% url 'productapp:catalog-detail' product.id %}">
                {{product.name}}<br>
              </a>
          Description: {{product.description}}<br>
          Category: {{product.category|upper}}<br>
          <br><br>
        {% endif %}
      {% endfor %}
    </p>


{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/category_list.html
{% extends 'base.html'  %}
{% load static %}

{% block content %}
<h1>Category List</h1>
<a href="{% url 'productapp:new-category' %}"><h5>Add New Category</h5></a>
<a href="{% url 'productapp:index' %}">  <h5>Go HOME</a></h5>

  {% for item in categories %}
    <h3><a href="{% url 'productapp:category-detail' item.id %}">{{item.name}}</a></h3>
    <ul>
      {% if item.slug %}
        <li>Description: {{item.slug}}</li>
      {% else %}
        <li>No slug available</li>
      {% endif %}

      <!-- <li>Price: ${{item.price}}</li>
      <li>Category: {{item.category}}</li> -->
    </ul>
  {% endfor %}
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/category_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="POST" action="{% url 'productapp:product-update' object.id %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" value="Update">Update</button>
  <a href="{% url 'productapp:category' %}" > Cancel </a>
</form>

{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/create_product.html
<!-- CURRENTLY LOADING THIS HTML FOR CREATE PRODUCT PAGE -->
{% extends 'base_new.html' %}

{% block create-form %}
<!-- ENCYTPE IS WHAT WAS MISSING -->
  <form method="POST" action="{% url 'productapp:create-product' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit">Submit</button>
    <a href="{% url 'productapp:catalog' %}" > Cancel </a>
  </form>
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/index.html
{% extends 'base.html'  %}

{%  block content %}
    <h1>Welcome Home...</h1>
    <a href="{% url 'productapp:catalog' %}"><h5>Product Catalog</h5></a>
    <a href="{% url 'productapp:create-product' %}">Add Product</a>
    <br><br>
    <a href="{% url 'productapp:category' %}"><h5>Category List</h5></a>
    <a href="{% url 'productapp:new-category' %}">Add Category</a>
    <br><br>
    {% if user.is_authenticated %}
      <a href="{% url 'customerapp:customers' %}"><h5>Customer List</h5></a>
      <a href="{% url 'customerapp:new-customer' %}">Add a Referral</a>
    {% else %}
      <br>
      <a href="{% url 'customerapp:new-customer' %}">Become a Customer</a>
    {% endif %}


  {% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/new_category.html
<!-- CURRENTLY LOADING THIS HTML FOR CREATE category PAGE -->
{% extends 'base_new.html' %}

{% block create-form %}
<!-- ENCYTPE IS WHAT WAS MISSING -->
  <form method="POST" action="{% url 'productapp:new-category' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit">Submit</button>
    <a href="{% url 'productapp:category' %}" > Cancel </a>
  </form>
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/product_confirm_delete.html
<!-- CURRENTLY LOADING THIS HTML FOR DELETE PRODUCT PAGE -->
{% extends 'base_confirm_delete.html' %}

{% block a-url %}
<a href="{% url 'productapp:catalog' %}" > <h3>Cancel</h3></a>
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/product_detail.html
{% extends 'base_detail.html' %}

{% block content %}
    <h1>{{object.name}}</h1>
        <ul>
          <li>{{object.description}}</li>
          <li>{{object.price}}</li>
          <li>{{object.category}}</li>
          <li>{{object.photo}}</li>
        </ul>
        <a href="{% url 'productapp:product-update' object.id %}"><h5>UPDATE</h5></a>
        <a href="{% url 'productapp:product-delete' object.id %}"><h5>DELETE</h5></a>

      <h3>Go back to <a href="{% url 'productapp:catalog' %}">Catalog</a></h3>
    <a href="{% url 'productapp:index' %}">  <h3>Go HOME</a></h3>
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/product_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <form method="POST" action="{% url 'productapp:create-product' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Submit">Submit</button>
    <a href="{% url 'productapp:catalog' %}" > Cancel </a>
  </form>
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/product_list.html
{% extends 'base_list.html'  %}

{% block obj-list %}
  <h1>Product Catalog</h1>
  <a href="{% url 'productapp:create-product' %}"><h5>Add New Product</h5></a>
  <a href="{% url 'productapp:index' %}">  <h5>Go HOME</a></h5>

    {% for item in products %}
    <a href="{% url 'productapp:catalog-detail' item.id %}"><h3>{{item.name}}</h3></a>
      <ul>

        {% if item.photo %}
          <img src="{{item.photo.url}}" alt="My Image" height="175" width="175">
        {% else %}
          <li>No photo available</li>
        {% endif %}

        <li>Description: {{item.description}}</li>
        <li>Price: ${{item.price}}</li>
        <li>Category: {{item.category}}</li>
      </ul>
    {% endfor %}
{% endblock %}

session-05/assignments/hw/inventory_app/productapp/templates/productapp/product_update.html
<!-- CURRENTLY LOADING THIS HTML FOR UPDATE PRODUCT PAGE -->
{% extends 'base_update.html' %}

{% block updateform %}
  <form method="POST" action="{% url 'productapp:product-update' object.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Update">Update</button>
    <a href="{% url 'productapp:catalog' %}" > Cancel </a>
  </form>
{% endblock %}