session-07/assignments/hw/shop-app/blog/urls.py
from django.urls import path

from blog import views

app_name='blog'

#URLPatterns for function based views
urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('new/', views.BlogCreate.as_view(), name='blog_new'),
    path('<int:pk>/update/', views.BlogUpdate.as_view(), name='blog_update'),
]

session-07/assignments/hw/shop-app/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog.urls')),
    path('restaurants/', include('restaurant.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


session-07/assignments/hw/shop-app/restaurant/urls.py
from django.urls import re_path
from django.utils import timezone
from django.views.generic import ListView, UpdateView, DetailView

from restaurant import views
from restaurant.forms import RestaurantForm, DishForm
from restaurant.models import Restaurant, Dish
from restaurant.views import RestaurantDetail, RestaurantCreate, DishCreate

app_name = 'restaurant'
urlpatterns = [
    # List latest 5 restaurants, ex.: /restaurants/
    re_path(r'^$',
            ListView.as_view(
                # model = Restaurant,
                queryset=Restaurant.objects.filter(date__lte=timezone.now()).order_by('date')[:5],
                context_object_name='latest_restaurant_list',
                template_name=' restaurant/restaurant_list.html'),
            name='restaurant_list'),

    # Restaurant details, ex.: /restaurants/1/
    re_path(r'^(?P<pk>\d+)/$',
            RestaurantDetail.as_view(),
            name='restaurant_detail'),

    # Create a restaurant, ex.: /restaurants/create/
    re_path(r'^create/$',
            RestaurantCreate.as_view(),
            name='restaurant_create'),

    # Update restaurant details, ex.: /restaurants/1/update/
    re_path(r'^(?P<pk>\d+)/update/$',
            UpdateView.as_view(
                model=Restaurant,
                template_name='restaurant/restaurant_update.html',
                form_class=RestaurantForm),
            name='restaurant_update'),

    # Restaurant dish details, ex: /restaurants/1/dishes/1/
    re_path(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$',
            DetailView.as_view(
                model=Dish,
                template_name='restaurant/dish_detail.html'),
            name='dish_detail'),

    # Create a restaurant dish, ex.: /restaurants/1/dishes/create/
    re_path(r'^restaurants/(?P<pk>\d+)/dishes/create/$',
            DishCreate.as_view(),
            name='dish_create'),

    # Update restaurant dish details, ex.: /restaurants/1/dishes/1/edit/
    re_path(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$',
            UpdateView.as_view(
                model=Dish,
                template_name='restaurant/restaurant_update.html',
                form_class=DishForm),
            name='dish_update'),

    # Create a restaurant review, ex.: /restaurants/1/reviews/create/
    re_path(r'^restaurants/(?P<pk>\d+)/reviews/create/$',
            views.review_create,
            name='review_create'),
]

session-07/assignments/hw/shop-app/restaurant/models.py
from django.db import models

# Create your models here.
# from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date


class Restaurant(models.Model):
    name = models.CharField(max_length=50)
    street = models.CharField(max_length=50, blank=True, null=True)
    number = models.PositiveIntegerField(blank=True, null=True)
    city = models.CharField(max_length=30)
    zipCode = models.CharField(max_length=5, blank=True, null=True)
    stateOrProvince = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=25, blank=True, null=True)
    telephone = models.IntegerField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('restaurant:restaurant_detail', kwargs={'pk': self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField('$ amount', max_digits=8, decimal_places=2, blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)
    image = models.ImageField(upload_to="restaurant/", blank=True, null=True)
    restaurant = models.ForeignKey(Restaurant, null=True, related_name='dishes', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'dish'
        verbose_name_plural = 'dishes'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurant:dish_detail', kwargs={'pkr': self.restaurant.pk, 'pk': self.pk}) #reverse mapping


RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))


class Review(models.Model):
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True


class RestaurantReview(Review):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

session-07/assignments/hw/shop-app/restaurant/forms.py
from django import forms
from restaurant.models import Restaurant, Dish


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        # fields = '__all__'
        exclude = ('user', 'date')

    def clean(self):
        pass


class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        # fields = '__all__'
        exclude = ('user', 'date')

    def clean(self):
        pass

session-07/assignments/hw/shop-app/restaurant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView

from restaurant.forms import RestaurantForm, DishForm
from restaurant.models import Restaurant, Dish, RestaurantReview, RATING_CHOICES


class RestaurantDetail(DetailView):
    model = Restaurant
    template_name = 'restaurant/restaurant_detail.html'
    extra_context = {'RATING_CHOICES': RATING_CHOICES}


class RestaurantCreate(LoginRequiredMixin, CreateView):
    model = Restaurant
    form_class = RestaurantForm
    template_name = 'restaurant/restaurant_create.html'
    success_url = reverse_lazy('restaurant:restaurant_list')
    login_url = 'login'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(RestaurantCreate, self).form_valid(form)


class DishCreate(LoginRequiredMixin, CreateView):
    model = Dish
    form_class = DishForm
    template_name = 'restaurant/restaurant_create.html'
    login_url = 'login'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DishCreate,self).form_valid(form)


def review_create(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    print(request)
    review = RestaurantReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        restaurant=restaurant)
    review.save()
    return HttpResponseRedirect(reverse('restaurant:restaurant_detail', args=(restaurant.id,)))

session-07/assignments/hw/shop-app/restaurant/templates/restaurant/dish_detail.html
{% extends '../base_restaurant.html' %}

{% block title %}Restaurant Dish Detail{% endblock title %}

{% block content %}
    {% if user %}
        <h3><a href="{% url 'restaurant:dish_update' object.id dish.id %}">Update Dish Information</a></h3>
    {% endif %}
    <h2>{{ dish.name }}</h2>
    <table>
        {% if object.image %}
        <tr>
            <td colspan="2"><image src="{{ dish.image.url }}" style="width:128px;height:128px;"></image></td>
        </tr>
        {% endif %}
        <tr>
            <td><b> Description </b></td>
            <td>{{ dish.description }}</td>
        </tr>
        <tr>
            <td><b> Price </b></td>
            <td>$ {{ object.price }}</td>
        </tr>
    </table>
{% endblock content %}

session-07/assignments/hw/shop-app/restaurant/templates/restaurant/restaurant_create.html
{% extends '../base_restaurant.html' %}

{% block title %}Restaurant Detail{% endblock title %}

{% block content %}
   <form method="post" action="" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
           {{ form.as_ul }}
        </table>
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'restaurant:restaurant_list' %}" > Cancel </a>
    </form>
{% endblock content %}

session-07/assignments/hw/shop-app/restaurant/templates/restaurant/restaurant_detail.html
{% extends '../base_restaurant.html' %}

{% block title %}Restaurant Detail{% endblock title %}

{% block content %}
    {% if user == object.user %}
        <h3><a href="{% url 'restaurant:restaurant_update' object.id %}">Update Restaurant Information</a></h3>
    {% endif %}
    <h2>{{ object.name }}</h2>
    <table>
        <tr>
            <td><b> Restaurant Address </b></td>
            <td>&nbsp;&nbsp;</td>
            <td>{{ object.street }}, {{ object.number }}, {{ object.city }}
            <br>{{ object.stateOrProvince }}, {{ object.zipCode }} - {{ object.country }}</td>
        </tr>
        <tr>
            <td><b> Restaurant URL </b></td>
            <td>&nbsp;&nbsp;</td>
            <td>{{ object.url }}</td>
        </tr>
    </table>
    <br>
    {% if object.dishes.all  %}
        <h3> Dishes offered by this restaurant: </h3>
        <ul>
        {% for dish in object.dishes.all %}
            <li><a href="{% url 'restaurant:dish_detail' object.id dish.id %}">{{ dish.name }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <label>There are no dishes added to this restaurant yet.</label><br>
    {% endif %}
    <a href="{% url 'restaurant:dish_create' object.id %}"> Add New Dish </a>
    <br><br>
    {% if object.restaurantreview_set.all %}
        <h3>Reviews by our customers: </h3>
        <ul>
        {% for review in object.restaurantreview_set.all %}
            <li>
                {{ review.rating }} Stars<br>
                {{ review.comment }}<br>
                Created by {{ review.user }} on {{ review.date }}
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    <h3> Add Review </h3>
    <form action="{% url 'restaurant:review_create' object.id %}" method="post">
        {% csrf_token %}
        Message: <textarea name="comment" id="comment" rows="4"></textarea>
        <p>Rating:
        <select name="rating" id="rating">
            {% for ratevalue, rate in RATING_CHOICES %}
            <option value={{ratevalue}}>{{ rate }} star{{ rate.0|pluralize }}</option>
            {% endfor %}
        </select></p>
        <input type="submit" value="Review" />
    </form>

{% endblock content %}

session-07/assignments/hw/shop-app/restaurant/templates/restaurant/restaurant_list.html
{% extends '../base_restaurant.html' %}

{% block title %}Restaurant List{% endblock title %}

{% block content %}
    {% if user %}<a href="{% url 'restaurant:restaurant_create' %}">Create New Restaurant</a>{% endif %}
    {% if latest_restaurant_list %}
        <table>
        {% for restaurant in latest_restaurant_list %}
            <tr><td>&nbsp;&nbsp;&nbsp;</td><td><a href="{% url 'restaurant:restaurant_detail' restaurant.id %}">{{ restaurant.name }}</a></td>
<!--                <td><a href="{% url 'restaurant:restaurant_update' restaurant.id %}" > Edit </a></td></tr>-->
        {% endfor %}
        </table>
    {% else %}
        <p>No restaurants are available.</p>
    {% endif %}
{% endblock content %}

session-07/assignments/hw/shop-app/restaurant/templates/restaurant/restaurant_update.html
{% extends '../base_restaurant.html' %}

{% block title %}Restaurant Detail{% endblock title %}

{% block content %}

    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'restaurant:restaurant_list' %}" > Cancel </a>
    </form>
{% endblock content %}