session-07/assignments/hw/shop-app/blog/urls.py
from django.urls import path

from blog import views

app_name='blog'

#URLPatterns for function based views
urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('new/', views.BlogCreate.as_view(), name='blog_new'),
    path('<int:pk>/update/', views.BlogUpdate.as_view(), name='blog_update'),
]

session-07/assignments/hw/shop-app/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog.urls')),
    path('restaurants/', include('restaurant.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


session-07/assignments/hw/shop-app/blog/models.py
from django.db import models


# Create your models here.
from django.utils import timezone


class Blog(models.Model):
    title = models.CharField(max_length=30)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

session-07/assignments/hw/shop-app/blog/forms.py
from django import forms

from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'created_date')

session-07/assignments/hw/shop-app/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.list import MultipleObjectMixin

from blog.models import Blog

class BlogList(ListView):
    template_name = 'blog/blog_list.html'
    model = Blog
    context_object_name = 'blogs'
    paginate_by = 2



class BlogDetail(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'


class BlogCreate(CreateView):
    model = Blog
    fields = ['title', 'text', 'created_date', 'published_date']
    template_name = 'blog/blog_new.html' # If not provided, searches for 'blog/blog_form.html'
    success_url = reverse_lazy('blog:blog_list')


class BlogUpdate(UpdateView):
    model = Blog
    fields = ['title', 'text', 'published_date']
    template_name = 'blog/blog_update.html'  # If not provided, searches for 'blog/blog_form.html'
    success_url = reverse_lazy('blog:blog_list')

session-07/assignments/hw/shop-app/blog/templates/blog/blog_detail.html
{% extends '../base.html' %}

{% block title %}Blog Detail{% endblock title %}

{% block content %}
    <h1>{{ blog.title }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {{ blog.text }} <br>
    {{ blog.created_date }} <br>
    {{ blog.published_date }} <br>
{% endblock content %}

session-07/assignments/hw/shop-app/blog/templates/blog/blog_list.html
{% extends '../base.html' %}

{% block title %}Blog List{% endblock title %}

{% block content %}
    {% if blogs %}
        <table>
        {% for blog in blogs %}
            <tr><td>&nbsp;&nbsp;&nbsp;</td><td><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></td>
                <td><a href="{% url 'blog:blog_update' blog.id %}" > Edit </a></td></tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No blogs are available.</p>
    {% endif %}
{% endblock content %}

session-07/assignments/hw/shop-app/blog/templates/blog/blog_new.html
{% extends '../base.html' %}

{% block title %}Create New Blog{% endblock title %}

{% block content %}
    <form method="post" action="{% url 'blog:blog_new' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'blog:blog_list' %}" > Cancel </a>
    </form>
{% endblock content %}

session-07/assignments/hw/shop-app/blog/templates/blog/blog_update.html
{% extends '../base.html' %}

{% block title %}Update Blog{% endblock title %}

{% block content %}
    <form method="post" >{% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'blog:blog_list' %}" > Cancel </a>
    </form>
{% endblock content %}