session-05/assignments/hw/inventory_app/customerapp/urls.py
from django.urls import include, path, re_path

from . import views
from customerapp.views import IndexView
from django.contrib.auth import views as auth_views

from customerapp.views import IndexView, CustomerListView, CustomerDetailView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView

app_name = 'customerapp'

urlpatterns = [
    # path('', IndexView.as_view(), name='index'),
    path('', CustomerListView.as_view(), name='customers'),

    # LEAKS DATA
    # path('new-customer', CustomerCreateView.as_view(), name='new-customer'),
    # re_path(r'^new-customer', CustomerCreateView.as_view(), name='new-customer'),

    path('<pk>', CustomerDetailView.as_view(), name='customer-detail'),
    path('<pk>/customer-update', CustomerUpdateView.as_view(), name='customer-update'),
    path('<pk>/customer-delete', CustomerDeleteView.as_view(), name='customer-delete'),

    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name='logout'),

    # path('accounts/profile/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),

    # re_path(r'^register/$', views.register, name='register'),
    # re_path(r'^register/$', views.register, name='register')

    # re_path(r'^new-customer/$', views.new_customer, name='new-customer'),

    re_path(r'^new-customer/$', CustomerCreateView.new_customer, name='new-customer'),

]

session-05/assignments/hw/inventory_app/inventory_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productapp.urls')),
    path('customers/', include('customerapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

session-05/assignments/hw/inventory_app/productapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views
from productapp.views import IndexView, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView
from productapp.views import CategoryListView, CategoryDetailView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView

from django.contrib.auth import views as auth_views

app_name = 'productapp'

urlpatterns = [

    # UPDATING TO generic class based views
    #
    # path('', views.index, name='index'),
    # path('catalog/', views.catalog, name='catalog'),
    # path('catalog/<int:id>', views.catalog_detail, name='catalog-detail'),
    # path('catalog/create-product', views.create_product, name='create-product'),


    path('', IndexView.as_view(), name='index'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('catalog/<pk>', ProductDetailView.as_view(), name='catalog-detail'),
    path('create-product', ProductCreateView.as_view(), name='create-product'),
    path('catalog/<pk>/update', ProductUpdateView.as_view(), name='product-update'),
    path('catalog/<pk>/delete', ProductDeleteView.as_view(), name='product-delete'),

    # catalog/category/ --> ERROR is looking for id
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/new', CategoryCreateView.as_view(), name='new-category'),

    path('category/<pk>', CategoryDetailView.as_view(), name='category-detail'),
    path('category/<pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),


    # path('category/<slug>', CategoryDetailView.as_view(), name='category-detail'),
    # path('category/<slug>/update', CategoryUpdateView.as_view(), name='category-update'),
    # path('category/<slug>/delete', CategoryDeleteView.as_view(), name='category-delete'),


    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name='logout'),

    # path('accounts/profile/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),

    re_path(r'^register/$', views.register, name='register'),
]

session-05/assignments/hw/inventory_app/customerapp/models.py
from django.db import models
from django.db.models import Model
from django.contrib.auth.models import User

# Create your models here.
class Customer(User):
    github = models.URLField(blank=True)

    def __str__(self):
        return self.email

session-05/assignments/hw/inventory_app/customerapp/forms.py
from django.forms import ModelForm
from productapp.models import Product

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

from customerapp.models import Customer

from django import forms

# class CustomerForm(forms.ModelForm):
#     model = Customer
#
#     class Meta:
#         fields = ['username', 'email', 'password', 'github']

class NewCustomerForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    github = forms.URLField()

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = Customer.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = Customer.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def clean_github(self):
        github = self.cleaned_data['github'].lower()
        return github

    def save(self, commit=True):
        # user = User.objects.create_user(
        customer = Customer.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1'],
            # self.cleaned_data['github']
        )
        return customer

session-05/assignments/hw/inventory_app/customerapp/views.py
from django.views import View
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect

from customerapp.models import Customer

from .forms import NewCustomerForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


from django.contrib import messages

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('Customer IndexView')

class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    # fields = ['username', 'email', 'password', 'github'] # LEAKS DATA FOR PASSWORD IN DB
    template_name = 'registration/new_customer.html'
    success_url = reverse_lazy('customerapp:customers')
    login_url = '/login/'


    # @login_required --> What if non-user; how to initially register
    def new_customer(request):
        if request.method == 'POST':
            f = NewCustomerForm(request.POST)
            if f.is_valid():
                f.save()
                messages.success(request, 'Account created successfully')
                return HttpResponseRedirect(reverse_lazy('customerapp:login'))
            else:
                return HttpResponse('Form not valid')
        else:
            f = NewCustomerForm()
        return render(request, 'registration/new_customer.html', {'form': f})



# class LoginView(View):
#     login_url = '/login/'
#     redirect_field_name = 'index'


class CustomerListView(ListView):
    model = Customer
    context_object_name = 'customers'


class CustomerDetailView(DetailView):
    model = Customer

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['customers'] = Customer.objects.all()
        context['customer_list'] = Customer.objects.all()

        return context


class CustomerUpdateView(UpdateView):
    model = Customer
    fields = ['username', 'email', 'password', 'github']
    template_name = 'customerapp/customer_update.html'
    success_url = reverse_lazy('customerapp:customers')
    template_name_suffix = '_update_form'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # context['customers'] = Customer.objects.all()
        context['customer_list'] = Customer.objects.all()

        return context

class CustomerDeleteView(DeleteView):
    model = Customer
    success_url = reverse_lazy('customerapp:customers')


class LoginView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'index'


class LogoutView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'catalog'


# @login_required
# def new_customer(request):
#     if request.method == 'POST':
#         f = NewCustomerForm(request.POST)
#         if f.is_valid():
#             f.save()
#             messages.success(request, 'Account created successfully')
#             return HttpResponseRedirect(reverse_lazy('customerapp:login'))
#         else:
#             return HttpResponse('Form not valid')
#     else:
#         f = NewCustomerForm()
#     return render(request, 'registration/new_customer.html', {'form': f})

session-05/assignments/hw/inventory_app/customerapp/templates/customerapp/customer_confirm_delete.html
<!-- CURRENTLY LOADING THIS HTML FOR DELETE PRODUCT PAGE -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete: <br> "{{object}}"</p>
    <button type="submit" value="Confirm">Confirm</button>
  </form>
  <a href="{% url 'customerapp:customers' %}" > <h3>Cancel</h3></a>
{% endblock %}

session-05/assignments/hw/inventory_app/customerapp/templates/customerapp/customer_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{object.username}}</h1>
        <ul>
          <li>{{object.email}}</li>
          {% if object.github %}
            <li>{{object.github}}</li>
          {% else %}
            <li>No Github available</li>
          {% endif %}
        </ul>

        <a href="{% url 'customerapp:customer-update' object.id %}"> <h5>UPDATE</h5> </a>
        <a href="{% url 'customerapp:customer-delete' object.id %}"> <h5>DELETE</h5> </a>

      <h3>Go back to <a href="{% url 'customerapp:customers' %}">Customer List</a></h3>
    <a href="{% url 'productapp:index' %}">  <h3>Go HOME</a></h3>
{% endblock %}

session-05/assignments/hw/inventory_app/customerapp/templates/customerapp/customer_list.html
{% extends 'base.html'  %}
{% load static %}

{% block content %}
    <h1>Customers List</h1>
    {% if user.is_authenticated %}
      <a href="{% url 'customerapp:new-customer' %}"><h5>Add a Referral</h5></a>
    {% else %}
      <a href="{% url 'customerapp:new-customer' %}"><h5>Become a Customer</h5></a>
    {% endif %}
    <a href="{% url 'productapp:index' %}">  <h5>Go HOME</a></h5>

      {% for item in customers %}
      {% if item.username %}
        <a href="{% url 'customerapp:customer-detail' item.id %}"><h3>{{item.username}}</h3></a>
      {% else %}
        <a href="{% url 'customerapp:customer-detail' item.id %}"> <h3>No username available</h3> </a>
      {% endif %}
        <ul>
          <li>{{item.email}}</li>
          {% if item.github %}
            <a href="{{item.github}}" target="_blank">{{item.github}}</a>
          {% else %}
            <li>No Github available</li>
          {% endif %}
        </ul>
      {% endfor %}

{% endblock %}

session-05/assignments/hw/inventory_app/customerapp/templates/customerapp/customer_update.html
<!-- CURRENTLY LOADING THIS HTML FOR UPDATE PRODUCT PAGE -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <form method="POST" action="{% url 'customerapp:customer-update' object.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Update">Update</button>
    <a href="{% url 'customerapp:customers' %}" > Cancel </a>
  </form>
{% endblock %}